#!/usr/bin/env python3
"""
plot_delos_sealevel.py
======================
Two-panel sea-level-rise risk figure for Delos island.

  Left panel  : Delos elevation map (0-200 m colour scale, green → brown)
  Right panel : Risk classification under a 0.8 m sea-level-rise scenario
                  -1 = Underwater     (elevation + rise < 0)
                   0 = High Danger    (0–5 m above adjusted sea level)
                   1 = Medium Danger  (5–10 m above adjusted sea level)
                   2 = Not in Danger  (> 10 m above adjusted sea level)

INPUTS
------
  plt_config.TIF_PATH     — Mapzen/AWS elevation raster clipped to Delos
                            (generated by raster/delos_mapzen_s2coast.py)
  plt_config.S2COAST_SHP  — S2Coast-2023 dissolved polyline for the coastline overlay
  plt_config.SEALEVEL_OUTPUT_PATH — output PNG path

DATA FLOW
---------
  raster/delos_mapzen_s2coast.py  →  delos_mapzen_s2coast.tif  →  this script  →  PNG
"""

import os
import struct
import sys

import numpy as np
import rasterio
import matplotlib
matplotlib.use("Agg")    # non-interactive backend
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
import matplotlib.ticker as mticker
import cartopy.io.shapereader as shpreader

# ---------------------------------------------------------------------------
# Import plot configuration (all paths live in plt_config.py)
# ---------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import downscaling.plt_config as cfg

# ---------------------------------------------------------------------------
# Paths — imported from plt_config so this script has no hardcoded machine paths
# ---------------------------------------------------------------------------
TIF_PATH    = cfg.TIF_PATH
OUTPUT_PATH = cfg.SEALEVEL_OUTPUT_PATH
S2COAST_SHP = cfg.S2COAST_SHP

# ---------------------------------------------------------------------------
# Sea-level-rise classification thresholds
# ---------------------------------------------------------------------------
SEA_LEVEL_RISE    = 0.8   # metres — IPCC RCP 4.5 median estimate for 2100
HIGH_DANGER_MAX   = 5.0   # adjusted elevation 0–5 m   → High Danger zone
MEDIUM_DANGER_MAX = 10.0  # adjusted elevation 5–10 m  → Medium Danger zone

# ---------------------------------------------------------------------------
# Matplotlib style (mirrors plot_ba_data.py for visual consistency)
# ---------------------------------------------------------------------------
plt.rcParams.update({
    "font.family":        "sans-serif",
    "font.sans-serif":    ["Arial", "Helvetica", "DejaVu Sans"],
    "font.size":          9,
    "axes.titlesize":     10,
    "axes.labelsize":     9,
    "xtick.labelsize":    7,
    "ytick.labelsize":    7,
    "axes.linewidth":     0.6,
    "xtick.major.width":  0.6,
    "ytick.major.width":  0.6,
    "xtick.major.size":   3,
    "ytick.major.size":   3,
    "xtick.direction":    "out",
    "ytick.direction":    "out",
    "axes.spines.top":    False,
    "axes.spines.right":  False,
    "figure.dpi":         150,
    "savefig.dpi":        150,
    "savefig.bbox":       "tight",
    "savefig.pad_inches": 0.02,
    "pdf.fonttype":       42,
    "ps.fonttype":        42,
})


# ---------------------------------------------------------------------------
# Grid helpers (shared logic with plot_ba_data.py)
# ---------------------------------------------------------------------------

def values_to_grid(lon, lat, values):
    """Map unstructured (lon, lat, value) triples onto the implicit regular grid."""
    lon_c = np.unique(np.round(lon, 9))
    lat_c = np.unique(np.round(lat, 9))
    grid  = np.full((len(lat_c), len(lon_c)), np.nan, dtype=float)
    lon_idx = {v: i for i, v in enumerate(lon_c)}
    lat_idx = {v: i for i, v in enumerate(lat_c)}
    for x, y, v in zip(np.round(lon, 9), np.round(lat, 9), values):
        grid[lat_idx[y], lon_idx[x]] = v
    return lon_c, lat_c, grid


def edges_from_centers(centers):
    """Convert cell-centre coordinates to cell-edge coordinates for pcolormesh."""
    c = np.asarray(centers, dtype=float)
    if len(c) == 1:
        return np.array([c[0] - 0.5, c[0] + 0.5])
    e = np.empty(len(c) + 1, dtype=float)
    e[1:-1] = (c[:-1] + c[1:]) / 2.0
    e[0]    = c[0]  - (c[1]  - c[0])  / 2.0
    e[-1]   = c[-1] + (c[-1] - c[-2]) / 2.0
    return e


# ---------------------------------------------------------------------------
# Coastline loader (same binary scan approach as plot_ba_data.py)
# ---------------------------------------------------------------------------

def load_coastlines(extent):
    """
    Return coastline line segments within 'extent' = [lon_min, lon_max, lat_min, lat_max].

    Tries S2Coast-2023 shapefile first; falls back to Natural Earth 10 m.
    """
    lon0, lon1, lat0, lat1 = extent
    pad = 0.01
    b0, b1, b2, b3 = lon0 - pad, lon1 + pad, lat0 - pad, lat1 + pad

    if os.path.exists(S2COAST_SHP):
        print("  Loading S2Coast shoreline…", flush=True)
        try:
            segments = []
            with open(S2COAST_SHP, "rb") as f:
                f.seek(100)   # skip file header
                while True:
                    header = f.read(8)
                    if len(header) < 8:
                        break
                    _, content_len_words = struct.unpack(">II", header)
                    content_bytes = content_len_words * 2
                    shape_raw = f.read(4)
                    if len(shape_raw) < 4:
                        break
                    shape_type = struct.unpack("<i", shape_raw)[0]
                    if shape_type not in (3, 5):
                        f.seek(content_bytes - 4, 1)
                        continue
                    bbox_raw = f.read(32)
                    if len(bbox_raw) < 32:
                        break
                    xmin, ymin, xmax, ymax = struct.unpack("<dddd", bbox_raw)
                    remaining = content_bytes - 36
                    if xmax < b0 or xmin > b1 or ymax < b2 or ymin > b3:
                        f.seek(remaining, 1)
                        continue
                    rest = f.read(remaining)
                    if len(rest) < 8:
                        continue
                    n_parts  = struct.unpack("<i", rest[0:4])[0]
                    n_points = struct.unpack("<i", rest[4:8])[0]
                    if n_parts < 1 or n_points < 2:
                        continue
                    parts_end = 8 + n_parts * 4
                    parts = list(struct.unpack(f"<{n_parts}i", rest[8:parts_end]))
                    pts_start = parts_end
                    pts_bytes = rest[pts_start: pts_start + n_points * 16]
                    if len(pts_bytes) < n_points * 16:
                        continue
                    points = np.frombuffer(pts_bytes, dtype="<f8").reshape(n_points, 2)
                    for p_i in range(n_parts):
                        p_start = parts[p_i]
                        p_end   = parts[p_i + 1] if p_i + 1 < n_parts else n_points
                        if p_end - p_start < 2:
                            continue
                        xy = points[p_start:p_end]
                        segments.append((xy[:, 0], xy[:, 1]))
            if segments:
                print(f"  S2Coast: {len(segments)} segment(s).", flush=True)
                return segments
            print("  S2Coast: 0 segments — falling back.", flush=True)
        except Exception as exc:
            print(f"  S2Coast error ({exc}) — falling back.", flush=True)

    print("  Using Natural Earth 10m coastline.", flush=True)
    shpfile = shpreader.natural_earth(resolution="10m", category="physical", name="coastline")
    segs = []
    for geom in shpreader.Reader(shpfile).geometries():
        parts = list(geom.geoms) if hasattr(geom, "geoms") else [geom]
        for part in parts:
            xy = np.array(part.coords)
            lx, ly = xy[:, 0], xy[:, 1]
            if lx.max() < b0 or lx.min() > b1 or ly.max() < b2 or ly.min() > b3:
                continue
            segs.append((lx, ly))
    return segs


def draw_coast(ax, coast_lines):
    """Draw all coastline segments on the given axes."""
    for lx, ly in coast_lines:
        ax.plot(lx, ly, color="#222222", linewidth=0.8, zorder=4)


# ---------------------------------------------------------------------------
# Axes setup
# ---------------------------------------------------------------------------

def setup_ax(ax, extent, show_ylabel=True):
    """Apply consistent geographic axes style: equal aspect, grid, fine ticks."""
    lon0, lon1, lat0, lat1 = extent
    ax.set_xlim(lon0, lon1)
    ax.set_ylim(lat0, lat1)
    ax.set_facecolor("white")
    ax.set_aspect("equal", adjustable="box")
    ax.xaxis.set_major_locator(mticker.MultipleLocator(0.005))
    ax.yaxis.set_major_locator(mticker.MultipleLocator(0.01))
    ax.xaxis.set_major_formatter(mticker.FormatStrFormatter("%.3f°"))
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.3f°"))
    ax.tick_params(axis="both", length=3, width=0.5, pad=2,
                   labelsize=7, direction="out")
    ax.tick_params(axis="y", labelleft=show_ylabel)
    ax.grid(color="#d0d0d0", linewidth=0.4, alpha=0.6, zorder=0)
    ax.set_xlabel("Longitude", fontsize=8, fontweight="bold")
    if show_ylabel:
        ax.set_ylabel("Latitude", fontsize=8, fontweight="bold")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # ── Load elevation raster ──────────────────────────────────────────────────
    # rasterio opens the GeoTIFF and returns the affine transform 't'.
    # t.c and t.f are the top-left corner (lon, lat); t.a and t.e are pixel size.
    with rasterio.open(TIF_PATH) as src:
        data   = src.read(1).astype(np.float64)   # (rows, cols); NaN = sea pixels
        t      = src.transform
        bounds = src.bounds

    height, width = data.shape

    # Pixel-centre coordinates from the affine transform.
    # t.e is negative because latitude decreases downward in the raster.
    lon_centers = t.c + (np.arange(width)  + 0.5) * t.a
    lat_centers = t.f + (np.arange(height) + 0.5) * t.e

    # ── Classify risk ──────────────────────────────────────────────────────────
    # Adjusted elevation = raw elevation − projected sea-level rise.
    # Sea pixels (originally NaN) remain NaN and will render as white background.
    adj_elev = data - SEA_LEVEL_RISE

    risk = np.where(np.isnan(data),                   np.nan,      # sea
           np.where(adj_elev < 0,                     -1,          # underwater
           np.where(adj_elev <= HIGH_DANGER_MAX,        0,          # high danger
           np.where(adj_elev <= MEDIUM_DANGER_MAX,      1, 2)))).astype(float)  # medium / safe

    # Print a summary of the classification result
    print(f"Underwater        : {int((risk == -1).sum())} pixels")
    print(f"High Danger       : {int((risk ==  0).sum())} pixels")
    print(f"Medium Danger     : {int((risk ==  1).sum())} pixels")
    print(f"Not in Danger     : {int((risk ==  2).sum())} pixels")

    # ── Geographic extent ──────────────────────────────────────────────────────
    pad    = 0.002   # small margin around the island
    extent = [bounds.left  - pad, bounds.right + pad,
              bounds.bottom - pad, bounds.top  + pad]

    coast_lines = load_coastlines(extent)

    # ── Cell edges for pcolormesh ──────────────────────────────────────────────
    lon_e = edges_from_centers(lon_centers)
    lat_e = edges_from_centers(lat_centers)

    # ── Colour maps ────────────────────────────────────────────────────────────
    # Elevation: continuous green (low) → brown (high), white for NaN (sea)
    elev_cmap = mcolors.LinearSegmentedColormap.from_list("elev_gb", [
        (0.00, "#1a7a1a"),   # forest green  ~0 m
        (0.15, "#5aaa32"),   # lime green    ~30 m
        (0.35, "#a0c840"),   # yellow-green  ~70 m
        (0.55, "#c8b464"),   # tan           ~110 m
        (0.75, "#a06428"),   # brown         ~150 m
        (1.00, "#6e3c14"),   # dark brown    ~200 m
    ])
    elev_cmap.set_bad(color="white")
    elev_norm = mcolors.Normalize(vmin=0, vmax=125)

    # Risk: four discrete classes (red → dark-orange → amber → green)
    risk_cmap = mcolors.ListedColormap(["#d62728", "#ff4500", "#ffbf00", "#2ca02c"])
    risk_cmap.set_bad(color="white")
    # BoundaryNorm maps class codes (-1, 0, 1, 2) to their respective colours
    risk_norm = mcolors.BoundaryNorm([-1.5, -0.5, 0.5, 1.5, 2.5], ncolors=4)

    # ── Figure layout ──────────────────────────────────────────────────────────
    data_aspect = (extent[3] - extent[2]) / (extent[1] - extent[0])
    panel_w = 3.8
    panel_h = panel_w * data_aspect
    fig_w   = panel_w * 2 + 2.0
    fig_h   = panel_h + 1.6

    fig = plt.figure(figsize=(fig_w, fig_h), constrained_layout=True)
    fig.set_constrained_layout_pads(w_pad=0.04, h_pad=0.08,
                                    hspace=0.02, wspace=0.04)
    fig.suptitle(
        "High Risk Areas of Delos based on\na 0.8m Sea Level Rise",
        fontsize=12, fontweight="bold", color="#111111", va="top",
    )

    gs = gridspec.GridSpec(1, 2, figure=fig)

    # ── Panel 1: Elevation ────────────────────────────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    setup_ax(ax1, extent, show_ylabel=True)
    ax1.set_title("Delos Elevation", fontsize=10, fontweight="bold",
                  color="#111111", pad=4)

    mesh1 = ax1.pcolormesh(lon_e, lat_e, np.ma.masked_invalid(data),
                            cmap=elev_cmap, norm=elev_norm,
                            shading="auto", zorder=2)
    draw_coast(ax1, coast_lines)

    cb1 = fig.colorbar(mesh1, ax=ax1, location="right",
                        shrink=0.85, aspect=20, pad=0.03)
    cb1.ax.set_title("m", fontsize=8, pad=6, loc="center", fontweight="bold")
    cb1.ax.tick_params(labelsize=7, length=3, width=0.6)

    # ── Panel 2: Risk classification ──────────────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    setup_ax(ax2, extent, show_ylabel=False)
    ax2.set_title("Areas Projected to be Underwater", fontsize=10,
                  fontweight="bold", color="#111111", pad=4)

    ax2.pcolormesh(lon_e, lat_e, np.ma.masked_invalid(risk),
                   cmap=risk_cmap, norm=risk_norm,
                   shading="auto", zorder=2)
    draw_coast(ax2, coast_lines)

    # Legend: only show categories that actually exist in the data
    risk_labels = {
        -1: ("Underwater (<0 m)",      "#d62728"),
         0: ("High Danger (0-5 m)",    "#ff4500"),
         1: ("Medium Danger (5-10 m)", "#ffbf00"),
         2: ("Not in Danger",          "#2ca02c"),
    }
    legend_handles = [
        mpatches.Patch(facecolor=color, edgecolor="#444444", linewidth=0.4,
                       label=label)
        for code, (label, color) in risk_labels.items()
        if int((risk == code).sum()) > 0
    ]
    ax2.legend(handles=legend_handles, loc="lower right", fontsize=6.5,
               framealpha=0.92, edgecolor="#cccccc", handlelength=1.2,
               handleheight=0.85, borderpad=0.6, labelspacing=0.45)

    # ── Save ──────────────────────────────────────────────────────────────────
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    fig.savefig(OUTPUT_PATH, dpi=150)
    plt.close(fig)
    print(f"\nSaved: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
