#!/usr/bin/env python3
"""
plot_ba_data.py
===============
Generate 7-panel publication figures from the bias-adjusted CORDEX ensemble.

DATA FLOW
---------
  ba_postprocessing.py  →  ba_<var>.csv  →  this script  →  ba_<var>.png

Each PNG shows one climate variable across seven panels:
  [a] Historical 1985-2005          (left column, top)
  [b] RCP 4.5 · 2041-2060  [c] RCP 8.5 · 2041-2060
  [d] RCP 4.5 · 2061-2080  [e] RCP 8.5 · 2061-2080
  [f] RCP 4.5 · 2081-2100  [g] RCP 8.5 · 2081-2100

All aesthetics (font sizes, colorbar geometry, variable colour scales) come
from downscaling/plt_config.py — do not edit this file for aesthetics.

USAGE
-----
  python plot_ba_data.py                       # all variables in plt_config.VARIABLES
  python plot_ba_data.py --var tmean           # single variable
  python plot_ba_data.py --var tmean precip_annual  # multiple specific variables
  python plot_ba_data.py --input-dir /path/to/csvs  # override input directory
"""

import os
import sys
import struct
import argparse

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")   # non-interactive backend; must come before pyplot import
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.ticker as mticker
import matplotlib.colors as mcolors
from matplotlib.ticker import MaxNLocator

import cartopy.io.shapereader as shpreader

# ---------------------------------------------------------------------------
# Locate the downscaling package relative to this script's position.
# This avoids the need for a machine-specific sys.path hack.
# ---------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import downscaling.plt_config as cfg

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
# The three future time slices analysed for each scenario
FUTURE_PERIODS = [(2041, 2060), (2061, 2080), (2081, 2100)]
SCENARIOS      = ["rcp45", "rcp85"]

# Coastline shapefile (S2Coast-2023, high-resolution Sentinel-2 product).
# Falls back to Natural Earth 10 m if the file is absent.
S2COAST_SHP = cfg.S2COAST_SHP

# Human-readable panel subtitles indexed by period key
_PANEL_SUBTITLES = {
    "historical":            "Historical  (1985-2005)",
    ("rcp45", 2041, 2060):  "RCP 4.5 · 2041-2060",
    ("rcp85", 2041, 2060):  "RCP 8.5 · 2041-2060",
    ("rcp45", 2061, 2080):  "RCP 4.5 · 2061-2080",
    ("rcp85", 2061, 2080):  "RCP 8.5 · 2061-2080",
    ("rcp45", 2081, 2100):  "RCP 4.5 · 2081-2100",
    ("rcp85", 2081, 2100):  "RCP 8.5 · 2081-2100",
}
_PANEL_LETTERS = list("abcdefg")


# ══════════════════════════════════════════════════════════════════════════════
#  Matplotlib style
# ══════════════════════════════════════════════════════════════════════════════

def _setup_style():
    """Apply project-wide rcParams from plt_config font/size settings."""
    plt.rcParams.update({
        "font.family":        "sans-serif",
        "font.sans-serif":    ["Arial", "Helvetica", "DejaVu Sans"],
        "font.size":          cfg.FONT_BASE,
        "axes.titlesize":     cfg.FONT_AXES_TITLE,
        "axes.labelsize":     cfg.FONT_AXES_LABEL,
        "xtick.labelsize":    cfg.FONT_TICK,
        "ytick.labelsize":    cfg.FONT_TICK,
        "axes.linewidth":     0.6,
        "xtick.major.width":  0.6,
        "ytick.major.width":  0.6,
        "xtick.major.size":   3,
        "ytick.major.size":   3,
        "xtick.direction":    "out",
        "ytick.direction":    "out",
        "axes.spines.top":    False,
        "axes.spines.right":  False,
        "figure.dpi":         cfg.PLOT_DPI,
        "savefig.dpi":        cfg.PLOT_DPI,
        "savefig.bbox":       "tight",
        "savefig.pad_inches": 0.02,
        "pdf.fonttype":       42,   # TrueType fonts embedded in PDF/PS — required by most journals
        "ps.fonttype":        42,
    })


# ══════════════════════════════════════════════════════════════════════════════
#  Auto colour levels
# ══════════════════════════════════════════════════════════════════════════════

def auto_levels(results, vcfg, n=15):
    """
    Compute nice contour levels from the 2nd–98th percentile of the actual
    ensemble data pooled across all 7 panels.

    Non-negative statistics (counts, sums) clamp the lower bound to 0.
    Falls back to vcfg['levels'] if the data are too sparse to compute.

    Parameters
    ----------
    results : dict  — {period_key: (n_points,) array}
    vcfg    : dict  — variable configuration from plt_config.VARIABLES
    n       : int   — target number of break values

    Returns
    -------
    levels : np.ndarray of sorted break values
    """
    all_vals = []
    for arr in results.values():
        if arr is not None:
            finite = arr[np.isfinite(arr)]
            if len(finite):
                all_vals.append(finite)

    if not all_vals:
        return np.unique(vcfg["levels"])

    combined = np.concatenate(all_vals)
    if len(combined) < 4:
        return np.unique(vcfg["levels"])

    stat_type = vcfg["stat_type"]
    vmin = float(np.percentile(combined, 2))
    vmax = float(np.percentile(combined, 98))

    # Override lower bound for non-negative statistics
    if "vmin" in vcfg:
        vmin = float(vcfg["vmin"])
    elif stat_type.startswith(("count_gt", "count_lt")) or stat_type in ("annual_sum", "precip_r99p"):
        vmin = 0.0

    if vmax <= vmin:
        return np.unique(vcfg["levels"])

    # MaxNLocator produces "nice" break values aligned to human-readable steps
    locator = MaxNLocator(nbins=n, steps=[1, 2, 2.5, 5, 10])
    lev = np.asarray(locator.tick_values(vmin, vmax))

    # Ensure 0 is included and is the lower bound for count/sum statistics
    if (stat_type.startswith(("count_gt", "count_lt")) or stat_type == "annual_sum") \
            and "vmin" not in vcfg:
        lev = lev[lev >= 0]
        if len(lev) == 0 or lev[0] > 0:
            lev = np.concatenate([[0.0], lev])
    else:
        tol = (vmax - vmin) * 0.02
        lev = lev[(lev >= vmin - tol) & (lev <= vmax + tol)]

    return lev if len(lev) >= 3 else np.unique(vcfg["levels"])


# ══════════════════════════════════════════════════════════════════════════════
#  Shoreline loading (binary shapefile reader — avoids GeoPandas dependency)
# ══════════════════════════════════════════════════════════════════════════════

def _scan_shp_lines(shp_path, lon0, lon1, lat0, lat1):
    """
    Read Polyline / Polygon records from a shapefile and return those that
    intersect the bounding box (lon0, lon1, lat0, lat1).

    Reads the binary .shp format directly (ESRI Shapefile spec § 3.3 Polygon,
    § 3.2 Polyline) to avoid requiring GeoPandas for this one operation.
    Only shape types 3 (Polyline) and 5 (Polygon) are handled.

    Returns a list of (lons, lats) arrays, one element per part of each record.
    """
    segments = []
    with open(shp_path, "rb") as f:
        f.seek(100)    # skip the 100-byte file header
        while True:
            header = f.read(8)
            if len(header) < 8:
                break
            # Record header: record number (big-endian) + content length in 16-bit words
            _, content_len_words = struct.unpack(">II", header)
            content_bytes = content_len_words * 2

            # First four bytes of record content = shape type (little-endian int32)
            shape_raw = f.read(4)
            if len(shape_raw) < 4:
                break
            shape_type = struct.unpack("<i", shape_raw)[0]

            if shape_type not in (3, 5):
                f.seek(content_bytes - 4, 1)
                continue

            # Bounding box of this record (8 bytes × 4 doubles)
            bbox_raw = f.read(32)
            if len(bbox_raw) < 32:
                break
            xmin, ymin, xmax, ymax = struct.unpack("<dddd", bbox_raw)
            remaining = content_bytes - 36

            # Skip records entirely outside the query bounding box
            if xmax < lon0 or xmin > lon1 or ymax < lat0 or ymin > lat1:
                f.seek(remaining, 1)
                continue

            rest = f.read(remaining)
            if len(rest) < 8:
                continue

            n_parts  = struct.unpack("<i", rest[0:4])[0]
            n_points = struct.unpack("<i", rest[4:8])[0]
            if n_parts < 1 or n_points < 2:
                continue

            # Part start indices into the point array
            parts_end = 8 + n_parts * 4
            parts     = list(struct.unpack(f"<{n_parts}i", rest[8:parts_end]))
            pts_start = parts_end
            pts_bytes = rest[pts_start: pts_start + n_points * 16]
            if len(pts_bytes) < n_points * 16:
                continue

            # Each point is two 64-bit doubles: (X/lon, Y/lat)
            points = np.frombuffer(pts_bytes, dtype="<f8").reshape(n_points, 2)
            for p_i in range(n_parts):
                p_start = parts[p_i]
                p_end   = parts[p_i + 1] if p_i + 1 < n_parts else n_points
                if p_end - p_start < 2:
                    continue
                xy = points[p_start:p_end]
                segments.append((xy[:, 0], xy[:, 1]))

    return segments


_COAST_CACHE = None   # module-level cache so the shapefile is parsed only once


def _load_coastlines(extent):
    """
    Return a list of (lon_array, lat_array) line segments covering 'extent'.

    Tries the high-resolution S2Coast-2023 shapefile first, then falls back
    to the Natural Earth 10 m coastline bundled with Cartopy.

    extent : [lon_min, lon_max, lat_min, lat_max]
    """
    global _COAST_CACHE
    if _COAST_CACHE is not None:
        return _COAST_CACHE

    lon0, lon1, lat0, lat1 = extent
    pad = 0.01   # small buffer to capture coast segments that start just outside
    b0, b1, b2, b3 = lon0 - pad, lon1 + pad, lat0 - pad, lat1 + pad

    if os.path.exists(S2COAST_SHP):
        print("  Loading S2Coast shoreline (sequential binary scan - may take ~60 s)...",
              flush=True)
        try:
            segs = _scan_shp_lines(S2COAST_SHP, b0, b1, b2, b3)
            print(f"  S2Coast: found {len(segs)} line segment(s) in extent.", flush=True)
            if segs:
                _COAST_CACHE = segs
                return _COAST_CACHE
            print("  S2Coast returned 0 segments - falling back to Natural Earth.", flush=True)
        except Exception as exc:
            print(f"  S2Coast scan error ({exc}) - falling back to Natural Earth.", flush=True)

    print("  Using Natural Earth 10m coastline.", flush=True)
    shpfile = shpreader.natural_earth(resolution="10m", category="physical", name="coastline")
    segs = []
    for geom in shpreader.Reader(shpfile).geometries():
        parts = list(geom.geoms) if hasattr(geom, "geoms") else [geom]
        for part in parts:
            xy = np.array(part.coords)
            lx, ly = xy[:, 0], xy[:, 1]
            # Skip segments entirely outside the padded bounding box
            if lx.max() < b0 or lx.min() > b1 or ly.max() < b2 or ly.min() > b3:
                continue
            segs.append((lx, ly))

    _COAST_CACHE = segs
    return _COAST_CACHE


# ══════════════════════════════════════════════════════════════════════════════
#  Grid helpers
# ══════════════════════════════════════════════════════════════════════════════

def values_to_grid(lon, lat, values):
    """
    Map unstructured (lon, lat, value) triples onto a regular 2-D grid.

    Delos points are not on a regular lat/lon grid, so we reconstruct the
    implicit regular grid by treating unique rounded coordinates as cell centres.

    Returns (lon_centers, lat_centers, grid) where grid has shape
    (n_lats, n_lons) and NaN where no point exists.
    """
    lon_c = np.unique(np.round(lon, 9))
    lat_c = np.unique(np.round(lat, 9))
    grid  = np.full((len(lat_c), len(lon_c)), np.nan, dtype=float)
    lon_idx = {v: i for i, v in enumerate(lon_c)}
    lat_idx = {v: i for i, v in enumerate(lat_c)}
    for x, y, v in zip(np.round(lon, 9), np.round(lat, 9), values):
        grid[lat_idx[y], lon_idx[x]] = v
    return lon_c, lat_c, grid


def edges_from_centers(centers):
    """
    Compute cell-edge coordinates from cell-centre coordinates.

    Uses midpoint rule for interior edges; extrapolates by half the first / last
    spacing for the boundary edges.  Needed for pcolormesh which expects edges.
    """
    c = np.asarray(centers, dtype=float)
    if len(c) == 1:
        return np.array([c[0] - 0.5, c[0] + 0.5])
    e = np.empty(len(c) + 1, dtype=float)
    e[1:-1] = (c[:-1] + c[1:]) / 2.0
    e[0]    = c[0]  - (c[1]  - c[0])  / 2.0
    e[-1]   = c[-1] + (c[-1] - c[-2]) / 2.0
    return e


# ══════════════════════════════════════════════════════════════════════════════
#  CSV input
# ══════════════════════════════════════════════════════════════════════════════

def load_results_from_csv(var_key, input_dir=None):
    """
    Read ba_<var_key>.csv written by ba_postprocessing.py.

    The CSV has columns: lon | lat | historical | rcp45_2041_2060 | … (7 cols).

    Returns
    -------
    lons    : (n_points,) float array
    lats    : (n_points,) float array
    results : dict mapping period keys to (n_points,) float arrays
              Period keys match _PANEL_SUBTITLES: 'historical' or (scen, yr_s, yr_e)
    """
    if input_dir is None:
        input_dir = cfg.INPUT_DIR
    path = os.path.join(input_dir, f"ba_{var_key}.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"CSV not found: {path}\n"
            f"Run ba_postprocessing.py --var {var_key} first."
        )

    df = pd.read_csv(path)
    lons = df["lon"].values
    lats = df["lat"].values

    results = {"historical": df["historical"].values}
    for scen in SCENARIOS:
        for yr_s, yr_e in FUTURE_PERIODS:
            col = f"{scen}_{yr_s}_{yr_e}"
            results[(scen, yr_s, yr_e)] = df[col].values

    return lons, lats, results


# ══════════════════════════════════════════════════════════════════════════════
#  Plotting helpers
# ══════════════════════════════════════════════════════════════════════════════

def _resolve_cmap(cmap_obj):
    """Accept either a Colormap instance or a string name."""
    if isinstance(cmap_obj, mcolors.Colormap):
        return cmap_obj
    return plt.get_cmap(cmap_obj)


def _make_ax(fig, gs_slot, extent, show_xtick_labels=False, show_ytick_labels=False):
    """
    Create one map axes with consistent ticks and aspect ratio.

    Tick intervals are set to 0.005° lon × 0.01° lat — appropriate for Delos
    (~5 km × 5 km grid spacing).  Tick labels are suppressed on non-edge panels
    to reduce clutter in the 4-row figure layout.
    """
    ax = fig.add_subplot(gs_slot)
    lon0, lon1, lat0, lat1 = extent
    ax.set_xlim(lon0, lon1)
    ax.set_ylim(lat0, lat1)
    ax.set_facecolor("white")
    ax.set_aspect("equal", adjustable="box")   # preserves correct shape of the island

    ax.xaxis.set_major_locator(mticker.MultipleLocator(0.005))
    ax.yaxis.set_major_locator(mticker.MultipleLocator(0.01))
    ax.xaxis.set_major_formatter(mticker.FormatStrFormatter("%.3f°"))
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.3f°"))

    ax.tick_params(axis="both", length=3, width=0.5, pad=2)
    ax.tick_params(axis="x", labelsize=cfg.FONT_TICK, labelbottom=show_xtick_labels)
    ax.tick_params(axis="y", labelsize=cfg.FONT_TICK, labelleft=show_ytick_labels)
    ax.grid(color="#d0d0d0", linewidth=0.4, alpha=0.6, zorder=0)

    return ax


def _draw_data(ax, lons, lats, values, cmap, norm):
    """Render data points as a pcolormesh on the given axes."""
    lon_c, lat_c, grid = values_to_grid(lons, lats, values)
    lon_e = edges_from_centers(lon_c)
    lat_e = edges_from_centers(lat_c)

    cmap_copy = cmap.copy()
    cmap_copy.set_bad(color="white")   # NaN cells (outside island outline) → white

    ax.pcolormesh(lon_e, lat_e, np.ma.masked_invalid(grid),
                  cmap=cmap_copy, norm=norm, shading="auto", zorder=2)


def _draw_coast(ax, coast_lines):
    """Overlay the coastline segments on the axes."""
    for lx, ly in coast_lines:
        ax.plot(lx, ly, color="#222222", linewidth=0.8, zorder=4)


def _annotate_panel(ax, letter, subtitle):
    """Add the panel letter badge and subtitle to the given axes."""
    ax.set_title(subtitle, fontsize=cfg.FONT_PANEL_SUBTITLE, pad=3,
                 loc="center", color="#222222", fontweight="bold")
    ax.text(0.04, 0.97, f"({letter})", transform=ax.transAxes,
            fontsize=cfg.FONT_PANEL_LETTER, fontweight="bold",
            va="top", ha="left", color="#111111", zorder=5,
            bbox=dict(boxstyle="square,pad=0.15", facecolor="white",
                      edgecolor="none", alpha=0.80))


def make_figure(results, lons, lats, vcfg, levels, coast_lines):
    """
    Build the 7-panel publication figure for one variable.

    Layout:
        Row 0: [a] Historical  (columns 0-1)
        Row 1: [b] rcp45 2041-2060  [c] rcp85 2041-2060
        Row 2: [d] rcp45 2061-2080  [e] rcp85 2061-2080
        Row 3: [f] rcp45 2081-2100  [g] rcp85 2081-2100

    A single shared colorbar is placed on the right of all panels.

    Parameters
    ----------
    results     : dict {period_key: (n_points,) array}
    lons, lats  : (n_points,) float arrays of Delos point coordinates
    vcfg        : variable config dict from plt_config.VARIABLES
    levels      : 1-D array of contour break values
    coast_lines : list of (lon_arr, lat_arr) segments from _load_coastlines()
    """
    cmap   = _resolve_cmap(vcfg["cmap"])
    extend = vcfg["extend"]
    levels = np.unique(levels)
    # BoundaryNorm maps data values to discrete color bins defined by 'levels'
    norm   = mcolors.BoundaryNorm(levels, ncolors=cmap.N, clip=False)

    pad  = cfg.MAP_PADDING
    lon0 = float(lons.min()) - pad;  lon1 = float(lons.max()) + pad
    lat0 = float(lats.min()) - pad;  lat1 = float(lats.max()) + pad
    extent = [lon0, lon1, lat0, lat1]

    # Figure height adapts to the island's lat/lon aspect ratio so panels are not distorted
    data_aspect = (lat1 - lat0) / (lon1 - lon0)
    panel_w_est = cfg.FIG_W * 0.73 / 2
    panel_h_est = panel_w_est * data_aspect
    fig_h       = max(4.0 * panel_h_est + 2.0, 8.0)

    fig = plt.figure(figsize=(cfg.FIG_W, fig_h), constrained_layout=True)
    fig.set_constrained_layout_pads(w_pad=0.02, h_pad=0.06, hspace=0.02, wspace=0.02)

    fig.suptitle(vcfg["title"] + "\n", fontsize=cfg.FONT_SUPTITLE, fontweight="bold",
                 va="top", color="#111111")

    gs      = gridspec.GridSpec(4, 4, figure=fig)
    letters = iter(_PANEL_LETTERS)
    all_axes = []

    # Row 0: Historical — occupies the left two columns
    ax_hist = _make_ax(fig, gs[0, 0:2], extent,
                       show_xtick_labels=False, show_ytick_labels=True)
    all_axes.append(ax_hist)
    hist_vals = results.get("historical")
    if hist_vals is not None and not np.all(np.isnan(hist_vals)):
        _draw_data(ax_hist, lons, lats, hist_vals, cmap, norm)
    else:
        ax_hist.text(0.5, 0.5, "No data", transform=ax_hist.transAxes,
                     ha="center", va="center", fontsize=cfg.FONT_NODATA, color="#888888")
    _draw_coast(ax_hist, coast_lines)
    _annotate_panel(ax_hist, next(letters), _PANEL_SUBTITLES["historical"])

    # Rows 1-3: Future scenario panels (2 columns × 3 rows = 6 panels)
    n_future_rows = len(FUTURE_PERIODS)
    for row_i, (yr_s, yr_e) in enumerate(FUTURE_PERIODS, start=1):
        is_bottom = (row_i == n_future_rows)
        for col_i, scen in enumerate(SCENARIOS):
            col_start = col_i * 2
            key  = (scen, yr_s, yr_e)
            ax   = _make_ax(fig, gs[row_i, col_start:col_start + 2], extent,
                            show_xtick_labels=is_bottom,
                            show_ytick_labels=(col_i == 0))
            all_axes.append(ax)
            values = results.get(key)
            if values is not None and not np.all(np.isnan(values)):
                _draw_data(ax, lons, lats, values, cmap, norm)
            else:
                ax.text(0.5, 0.5, "No data", transform=ax.transAxes,
                        ha="center", va="center", fontsize=cfg.FONT_NODATA, color="#888888")
            _draw_coast(ax, coast_lines)
            _annotate_panel(ax, next(letters), _PANEL_SUBTITLES[key])

    # Shared axis labels
    fig.supylabel("Latitude",  fontsize=cfg.FONT_AXES_LABEL, fontweight="bold")
    fig.supxlabel("Longitude", fontsize=cfg.FONT_AXES_LABEL, fontweight="bold")

    # Single colorbar to the right of all panels
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cb = fig.colorbar(sm, ax=all_axes, location="right", extend=extend,
                      shrink=cfg.CBAR_SHRINK, aspect=cfg.CBAR_ASPECT, pad=0.02)
    cb.ax.set_title(vcfg["unit"], fontsize=cfg.FONT_CBAR_LABEL, pad=8, loc="center")
    cb.ax.tick_params(labelsize=cfg.FONT_CBAR_TICK, length=4, width=0.8)

    # Thin the tick labels when there are many break values
    if len(levels) > 20:
        cb.set_ticks(levels[::4])

    return fig


# ══════════════════════════════════════════════════════════════════════════════
#  Main
# ══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="Generate bias-adjusted CORDEX ensemble plots from CSVs")
    parser.add_argument("--var", nargs="+", default=None,
                        help="Variable keys to plot (default: all defined in plt_config.VARIABLES)")
    parser.add_argument("--input-dir", default=None,
                        help="Directory containing ba_*.csv files (default: cfg.INPUT_DIR)")
    parser.add_argument("--output-dir", default=None,
                        help="Directory for output .png files (default: cfg.OUTPUT_DIR)")
    args = parser.parse_args()

    input_dir  = args.input_dir  if args.input_dir  else cfg.INPUT_DIR
    output_dir = args.output_dir if args.output_dir else cfg.OUTPUT_DIR

    _setup_style()
    os.makedirs(output_dir, exist_ok=True)

    var_keys = args.var if args.var else list(cfg.VARIABLES.keys())

    # Load the coastline once, using the geographic extent of the first variable's data
    first_key = var_keys[0]
    lons, lats, _ = load_results_from_csv(first_key, input_dir)
    extent = [lons.min() - cfg.MAP_PADDING, lons.max() + cfg.MAP_PADDING,
              lats.min() - cfg.MAP_PADDING, lats.max() + cfg.MAP_PADDING]
    coast_lines = _load_coastlines(extent)

    for var_key in var_keys:
        vcfg = cfg.VARIABLES[var_key]
        print(f"-- {var_key}  ({vcfg['stat_type']}) --")

        lons, lats, results = load_results_from_csv(var_key, input_dir)

        # Apply the per-variable scale factor (e.g. ×10 converts annual → decadal)
        scale = vcfg.get("scale", 1.0)
        if scale != 1.0:
            results = {k: v * scale if v is not None else None
                       for k, v in results.items()}

        # Choose break levels: use exactly cfg levels, or auto-compute from data
        if vcfg.get("use_config_levels", False):
            levels = np.unique(vcfg["levels"])
        else:
            levels = auto_levels(results, vcfg)
        print(f"  levels: {levels[0]:.4g} ... {levels[-1]:.4g}  ({len(levels)} breaks)",
              flush=True)

        fig   = make_figure(results, lons, lats, vcfg, levels, coast_lines)
        fname = os.path.join(output_dir, f"ba_{var_key}.png")
        fig.savefig(fname, dpi=cfg.PLOT_DPI)
        plt.close(fig)
        print(f"  -> saved: {fname}\n")

    print("Done.")


if __name__ == "__main__":
    main()
